"""init

Revision ID: 57beb47d38d3
Revises: 
Create Date: 2021-12-02 18:11:42.551720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57beb47d38d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('identifier', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuels_identifier'), 'fuels', ['identifier'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_codename'), 'roles', ['codename'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('identifier', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_identifier'), 'users', ['identifier'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('autos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.Column('identifier', sa.String(length=150), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fuel'], ['fuels.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autos_fuel'), 'autos', ['fuel'], unique=False)
    op.create_index(op.f('ix_autos_identifier'), 'autos', ['identifier'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('invited', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('user_identifier', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_identifier')
    )
    op.create_index(op.f('ix_invites_hash'), 'invites', ['hash'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('receiver', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_is_active'), 'transactions', ['is_active'], unique=False)
    op.create_table('users_roles',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user', 'role')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('auto', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['auto'], ['autos.id'], ),
    sa.ForeignKeyConstraint(['driver'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_auto'), 'trips', ['auto'], unique=False)
    op.create_index(op.f('ix_trips_driver'), 'trips', ['driver'], unique=False)
    op.create_index(op.f('ix_trips_is_deleted'), 'trips', ['is_deleted'], unique=False)
    op.create_table('trip_passengers',
    sa.Column('passenger', sa.Integer(), nullable=False),
    sa.Column('trip', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passenger'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('passenger', 'trip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_passengers')
    op.drop_index(op.f('ix_trips_is_deleted'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver'), table_name='trips')
    op.drop_index(op.f('ix_trips_auto'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('users_roles')
    op.drop_index(op.f('ix_transactions_is_active'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_invites_hash'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_autos_identifier'), table_name='autos')
    op.drop_index(op.f('ix_autos_fuel'), table_name='autos')
    op.drop_table('autos')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_identifier'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_codename'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_fuels_identifier'), table_name='fuels')
    op.drop_table('fuels')
    # ### end Alembic commands ###
